language: julia

DOCUMENTER_DEBUG = true

os:
  - linux
  - osx

julia:
  - 1.0

# Use the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
# matrix:
#   allow_failures:
#     - julia: nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PACKAGE_NAME")); include(joinpath("docs", "make.jl"))'
